/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
}
