/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    MenuIcon: typeof import('./src/components/Menu/menu-icon.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPicker: typeof import('./src/components/SelectPicker/index.vue')['default']
    UploadImage: typeof import('./src/components/UploadImage/index.vue')['default']
  }
}
